# Generated by Django 3.2 on 2022-01-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=50, verbose_name='基因编码')),
                ('gene_length', models.PositiveSmallIntegerField(verbose_name='基因长度')),
                ('gene_seq', models.TextField(verbose_name='基因序列')),
            ],
        ),
    ]
