# Generated by Django 3.2 on 2022-01-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataModel',
            new_name='Data',
        ),
    ]
